services:
# BoTS Version 1
  bots1:
    image: splunk/splunk:8.2.3
    container_name: bots1
    volumes:
      - "./apps/botsv1:/tmp/apps"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_APPS_URL=/tmp/apps/fortinet-fortigate-add-on-for-splunk_167.tgz,/tmp/apps/splunk-add-on-for-microsoft-sysmon_810.tgz,/tmp/apps/splunk-add-on-for-microsoft-windows_800.tgz,/tmp/apps/splunk-app-for-stream_720-stripped.tgz,/tmp/apps/splunk-ta-for-suricata_233.tgz,/tmp/apps/url-toolbox_192.tgz,/tmp/apps/splunk-add-on-for-tenable_514.tgz,/tmp/apps/boss-of-the-soc-bots-investigation-workshop-for-splunk_122.tgz,https://s3.amazonaws.com/botsdataset/botsv1/botsv1-attack-only.tgz
    ports:
      - '8000:8000'
# BoTS Version 2
  bots2:
    image: splunk/splunk:8.2.3
    container_name: bots2
    volumes:
      - "./apps/botsv2:/tmp/apps"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_APPS_URL=/tmp/apps/base64_11.tgz,/tmp/apps/jellyfisher_101.tgz,/tmp/apps/palo-alto-networks-add-on-for-splunk_811.tgz,/tmp/apps/sa-investigator-for-enterprise-security_400.tgz,/tmp/apps/splunk-add-on-for-apache-web-server_210.tgz,/tmp/apps/splunk-add-on-for-microsoft-cloud-services_522.tgz,/tmp/apps/splunk-add-on-for-microsoft-sysmon_1062.tgz,/tmp/apps/splunk-add-on-for-microsoft-windows_880.tgz,/tmp/apps/splunk-add-on-for-symantec-endpoint-protection_341.tgz,/tmp/apps/splunk-add-on-for-unix-and-linux_850.tgz,/tmp/apps/splunk-app-for-osquery_10.tgz,/tmp/apps/splunk-app-for-stream_811.tgz,/tmp/apps/splunk-common-information-model-cim_4180.tgz,/tmp/apps/splunk-security-essentials_371.tgz,/tmp/apps/splunk-ta-for-suricata_233.tgz,/tmp/apps/ssl-certificate-checker_420.tgz,/tmp/apps/url-toolbox_192.tgz,/tmp/apps/website-monitoring_294.tgz,/tmp/apps/boss-of-the-soc-bots-advanced-apt-hunting-companion-app-for-splunk_11.tgz,https://s3.amazonaws.com/botsdataset/botsv2/botsv2_data_set_attack_only.tgz
    ports:
      - '8020:8000'
# BoTS Version 3
  bots3:
    image: splunk/splunk:8.2.3
    container_name: bots3
    volumes:
      - "./apps/botsv3:/tmp/apps"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
      - SPLUNK_APPS_URL=/tmp/apps/amazon-guardduty-add-on-for-splunk_104.tgz,/tmp/apps/cisco-endpoint-security-analytics-cesa_406.tgz,/tmp/apps/code42-for-splunk-legacy_3012.tgz,/tmp/apps/decrypt_231.tgz,/tmp/apps/microsoft-365-app-for-splunk_331.tgz,/tmp/apps/osquery-app-for-splunk_060.tgz,/tmp/apps/sa-cim_vladiator_200.tgz,/tmp/apps/splunk-add-on-for-amazon-web-services-aws_730.tgz,/tmp/apps/splunk-add-on-for-cisco-asa_511.tgz,/tmp/apps/splunk-add-on-for-microsoft-azure_403.tgz,/tmp/apps/splunk-add-on-for-microsoft-cloud-services_522.tgz,/tmp/apps/splunk-add-on-for-microsoft-office-365_430.tgz,/tmp/apps/splunk-add-on-for-microsoft-office-365-reporting-web-service_201.tgz,/tmp/apps/splunk-add-on-for-microsoft-sysmon_1062.tgz,/tmp/apps/splunk-add-on-for-microsoft-windows_880.tgz,/tmp/apps/splunk-add-on-for-symantec-endpoint-protection_341.tgz,/tmp/apps/splunk-add-on-for-tenable_514.tgz,/tmp/apps/splunk-add-on-for-unix-and-linux_850.tgz,/tmp/apps/splunk-app-for-stream_811.tgz,/tmp/apps/splunk-common-information-model-cim_4180.tgz,/tmp/apps/splunk-es-content-update_4300.tgz,/tmp/apps/splunk-security-essentials_371.tgz,/tmp/apps/ta-for-code42-app-for-splunk_3012.tgz,/tmp/apps/url-toolbox_192.tgz,/tmp/apps/virustotal-workflow-actions-for-splunk_020.tgz,https://botsdataset.s3.amazonaws.com/botsv3/botsv3_data_set.tgz
    ports:
      - '8030:8000'
# BoTS CTF Scoreboard
  # scoreboard:
  #   image: splunk/splunk:8.2.3
  #   container_name: bots-scoreboard
  #   volumes:
  #     - "./apps/ctf_scoreboard:/tmp/apps"
  #   environment:
  #       - SPLUNK_START_ARGS=--accept-license
  #       - SPLUNK_PASSWORD=changeme
  #       - SPLUNK_APPS_URL=/tmp/apps/splunk-SA-ctf_scoreboard-bef2d5c.tar.gz,/tmp/apps/splunk-SA-ctf_scoreboard_admin-7a694a5.tar.gz
  #   ports:
  #       - '8123:8000'